# Async Await

It is newer way of handling async task. If the `await` keyword is encountered inside an async function, the code execution is passed and the control is passed to the next statement after the async function invocation. The rest of the code inside the async function is added to the micro task queue and is only resumed once the entire sync code execution is completed. 

This can be mainly used for fetch and async task handlings. This avoids the callback model of Promise. To catch the error, ie to handle the catch block, we can wrap the entire async body in try catch.

```
async function call(){
  console.log('Me second')
  const data=await fetch('https://jsonplaceholder.typicode.com/todos/1')
  console.log(data)
}

console.log('Me first')
call()
console.log('Me Last')
```

console
```
// Me first
// Me second
// Me Last
// [.....data]
```